In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import the Data set csv
data=pd.read_csv("data.csv")
print(data)

              Day Campaign status                    Campaign Budget name  \
0      2023-11-18          Paused     New Arrivals 05/10/2023          --
1      2023-11-13          Paused     New Arrivals 05/10/2023          --
2      2024-01-02          Paused   Display-Campaign Group 01          --
3      2024-01-07          Paused   Display-Campaign Group 01          --
4      2023-10-10          Paused     New Arrivals 05/10/2023          --
...           ...             ...                         ...         ...
89910  2023-06-06         Removed  GOOGLE-home and garden CPC          --
89911  2023-10-12         Removed  GOOGLE-home and garden CPC          --
89912  2023-08-15         Removed         Campaign for 278904          --
89913  2023-10-18         Removed         Campaign for 278904          --
89914  2023-10-20         Removed         Campaign for 278904          --

      Currency code  Budget Budget type   Status             Status reasons  \
0               GBP     3.0       Daily   Paused   campaign paused; unknown
1               GBP     3.0       Daily   Paused   campaign paused; unknown
2               GBP     5.0       Daily   Paused   campaign paused; unknown
3               GBP     5.0       Daily   Paused   campaign paused; unknown
4               GBP     3.0       Daily   Paused   campaign paused; unknown
...             ...     ...         ...      ...                        ...
89910           GBP     1.0       Daily  Removed  campaign removed; unknown
89911           GBP     1.0       Daily  Removed  campaign removed; unknown
89912           GBP    10.0       Daily  Removed           campaign removed
89913           GBP    10.0       Daily  Removed           campaign removed
89914           GBP    10.0       Daily  Removed           campaign removed

       Clicks    CTR  Avg. CPC  Impr.  Avg. cost  Cost  Conv. value  \
0           1  0.62%      0.16    162       0.16  0.16         0.00
1           3  1.15%      0.18    261       0.18  0.53         0.00
2           0     --      0.00      0       0.00  0.00         0.00
3           0     --      0.00      0       0.00  0.00         0.00
4          17  0.72%      0.23   2373       0.23  3.83       118.46
...       ...    ...       ...    ...        ...   ...          ...
89910       0     --      0.00      0       0.00  0.00         0.00
89911       0     --      0.00      0       0.00  0.00         0.00
89912       0     --      0.00      0       0.00  0.00         0.00
89913       0     --      0.00      0       0.00  0.00         0.00
89914       0     --      0.00      0       0.00  0.00         0.00

      Campaign type          Bid strategy type Campaign group
0          Shopping                Target ROAS             --
1          Shopping                Target ROAS             --
2           Display                Target ROAS             --
3           Display                Target ROAS             --
4          Shopping                Target ROAS             --
...             ...                        ...            ...
89910      Shopping             CPC (enhanced)             --
89911      Shopping             CPC (enhanced)             --
89912      Shopping  Maximize Conversion Value             --
89913      Shopping  Maximize Conversion Value             --
89914      Shopping  Maximize Conversion Value             --

[89915 rows x 19 columns]

In [23]:
#viewing the first few data
data.head()

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,2023-11-18,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,1,0.62%,0.16,162,0.16,0.16,0.00,Shopping,Target ROAS,--
1,2023-11-13,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,3,1.15%,0.18,261,0.18,0.53,0.00,Shopping,Target ROAS,--
2,2024-01-02,Paused,Display-Campaign Group 01,--,GBP,5.0,Daily,Paused,campaign paused; unknown,0,--,0.00,0,0.00,0.00,0.00,Display,Target ROAS,--
3,2024-01-07,Paused,Display-Campaign Group 01,--,GBP,5.0,Daily,Paused,campaign paused; unknown,0,--,0.00,0,0.00,0.00,0.00,Display,Target ROAS,--
4,2023-10-10,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,17,0.72%,0.23,2373,0.23,3.83,118.46,Shopping,Target ROAS,--

In [24]:
#viewing last few data
data.tail()

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
89910,2023-06-06,Removed,GOOGLE-home and garden CPC,--,GBP,1.0,Daily,Removed,campaign removed; unknown,0,--,0.0,0,0.0,0.0,0.0,Shopping,CPC (enhanced),--
89911,2023-10-12,Removed,GOOGLE-home and garden CPC,--,GBP,1.0,Daily,Removed,campaign removed; unknown,0,--,0.0,0,0.0,0.0,0.0,Shopping,CPC (enhanced),--
89912,2023-08-15,Removed,Campaign for 278904,--,GBP,10.0,Daily,Removed,campaign removed,0,--,0.0,0,0.0,0.0,0.0,Shopping,Maximize Conversion Value,--
89913,2023-10-18,Removed,Campaign for 278904,--,GBP,10.0,Daily,Removed,campaign removed,0,--,0.0,0,0.0,0.0,0.0,Shopping,Maximize Conversion Value,--
89914,2023-10-20,Removed,Campaign for 278904,--,GBP,10.0,Daily,Removed,campaign removed,0,--,0.0,0,0.0,0.0,0.0,Shopping,Maximize Conversion Value,--

In [25]:
#calculate the row and column of the data(records)
print(data.shape)
n_records=data.shape[0]
print("Total number of Records : ",n_records)

(89915, 19)
Total number of Records :  89915

In [26]:
#checking the null data
data.isnull()

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89910,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
89911,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
89912,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
89913,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
89914,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
#checking the sum of missing
data.isnull().sum()

Day                  0
Campaign status      0
Campaign             0
Budget name          0
Currency code        0
Budget               0
Budget type          0
Status               0
Status reasons       0
Clicks               0
CTR                  0
Avg. CPC             0
Impr.                0
Avg. cost            0
Cost                 0
Conv. value          0
Campaign type        0
Bid strategy type    0
Campaign group       0
dtype: int64

In [28]:
print(data[data.notnull()])

              Day Campaign status                    Campaign Budget name  \
0      2023-11-18          Paused     New Arrivals 05/10/2023          --
1      2023-11-13          Paused     New Arrivals 05/10/2023          --
2      2024-01-02          Paused   Display-Campaign Group 01          --
3      2024-01-07          Paused   Display-Campaign Group 01          --
4      2023-10-10          Paused     New Arrivals 05/10/2023          --
...           ...             ...                         ...         ...
89910  2023-06-06         Removed  GOOGLE-home and garden CPC          --
89911  2023-10-12         Removed  GOOGLE-home and garden CPC          --
89912  2023-08-15         Removed         Campaign for 278904          --
89913  2023-10-18         Removed         Campaign for 278904          --
89914  2023-10-20         Removed         Campaign for 278904          --

      Currency code  Budget Budget type   Status             Status reasons  \
0               GBP     3.0       Daily   Paused   campaign paused; unknown
1               GBP     3.0       Daily   Paused   campaign paused; unknown
2               GBP     5.0       Daily   Paused   campaign paused; unknown
3               GBP     5.0       Daily   Paused   campaign paused; unknown
4               GBP     3.0       Daily   Paused   campaign paused; unknown
...             ...     ...         ...      ...                        ...
89910           GBP     1.0       Daily  Removed  campaign removed; unknown
89911           GBP     1.0       Daily  Removed  campaign removed; unknown
89912           GBP    10.0       Daily  Removed           campaign removed
89913           GBP    10.0       Daily  Removed           campaign removed
89914           GBP    10.0       Daily  Removed           campaign removed

       Clicks    CTR  Avg. CPC  Impr.  Avg. cost  Cost  Conv. value  \
0           1  0.62%      0.16    162       0.16  0.16         0.00
1           3  1.15%      0.18    261       0.18  0.53         0.00
2           0     --      0.00      0       0.00  0.00         0.00
3           0     --      0.00      0       0.00  0.00         0.00
4          17  0.72%      0.23   2373       0.23  3.83       118.46
...       ...    ...       ...    ...        ...   ...          ...
89910       0     --      0.00      0       0.00  0.00         0.00
89911       0     --      0.00      0       0.00  0.00         0.00
89912       0     --      0.00      0       0.00  0.00         0.00
89913       0     --      0.00      0       0.00  0.00         0.00
89914       0     --      0.00      0       0.00  0.00         0.00

      Campaign type          Bid strategy type Campaign group
0          Shopping                Target ROAS             --
1          Shopping                Target ROAS             --
2           Display                Target ROAS             --
3           Display                Target ROAS             --
4          Shopping                Target ROAS             --
...             ...                        ...            ...
89910      Shopping             CPC (enhanced)             --
89911      Shopping             CPC (enhanced)             --
89912      Shopping  Maximize Conversion Value             --
89913      Shopping  Maximize Conversion Value             --
89914      Shopping  Maximize Conversion Value             --

[89915 rows x 19 columns]

In [29]:
#Checking the column names
for col in data.columns:
    print(col)

Day
Campaign status
Campaign
Budget name
Currency code
Budget
Budget type
Status
Status reasons
Clicks
CTR
Avg. CPC
Impr.
Avg. cost
Cost
Conv. value
Campaign type
Bid strategy type
Campaign group

In [30]:
#Checking 1st row elements of dataframe
data.iloc[0]

Day                                2023-11-18
Campaign status                        Paused
Campaign              New Arrivals 05/10/2023
Budget name                                --
Currency code                             GBP
Budget                                    3.0
Budget type                             Daily
Status                                 Paused
Status reasons       campaign paused; unknown
Clicks                                      1
CTR                                     0.62%
Avg. CPC                                 0.16
Impr.                                     162
Avg. cost                                0.16
Cost                                     0.16
Conv. value                               0.0
Campaign type                        Shopping
Bid strategy type                 Target ROAS
Campaign group                             --
Name: 0, dtype: object

In [31]:
#Checking 1st column datas
data.iloc[0:-1,0]

0        2023-11-18
1        2023-11-13
2        2024-01-02
3        2024-01-07
4        2023-10-10
            ...
89909    2024-03-25
89910    2023-06-06
89911    2023-10-12
89912    2023-08-15
89913    2023-10-18
Name: Day, Length: 89914, dtype: object

### Clean the data set

In [32]:
#Checking how many ' ?' in every columns (null values given as ' ?')
data.isin(['--']).sum()

Day                      0
Campaign status          0
Campaign                 0
Budget name          88447
Currency code            0
Budget                   0
Budget type              0
Status                   0
Status reasons           0
Clicks                   0
CTR                  83948
Avg. CPC                 0
Impr.                    0
Avg. cost                0
Cost                     0
Conv. value              0
Campaign type            0
Bid strategy type        0
Campaign group       80740
dtype: int64

In [33]:
#replace all ? as null value
null_data = data.replace(" ?",np.NaN)

#check wheter all ? changed as null
print("\n----checking all ? data changed as null----")
print(null_data.isnull().sum())

#drop the null value rows
notNull_data=null_data.dropna()
print("\n---checking whether all null data cleared----")
print(notNull_data.isnull().sum())

----checking all ? data changed as null----
Day                  0
Campaign status      0
Campaign             0
Budget name          0
Currency code        0
Budget               0
Budget type          0
Status               0
Status reasons       0
Clicks               0
CTR                  0
Avg. CPC             0
Impr.                0
Avg. cost            0
Cost                 0
Conv. value          0
Campaign type        0
Bid strategy type    0
Campaign group       0
dtype: int64

---checking whether all null data cleared----
Day                  0
Campaign status      0
Campaign             0
Budget name          0
Currency code        0
Budget               0
Budget type          0
Status               0
Status reasons       0
Clicks               0
CTR                  0
Avg. CPC             0
Impr.                0
Avg. cost            0
Cost                 0
Conv. value          0
Campaign type        0
Bid strategy type    0
Campaign group       0
dtype: int64

In [34]:
#checking the duplicate data entry
print("Duplicate Entries : ",notNull_data.duplicated().sum())

#drop all duplicated entry
clean_data=notNull_data.drop_duplicates()
print("\n---Check whether there are duplicate data present after the clean---- ")
print("\nDuplicate data : ",clean_data.duplicated().sum())

Duplicate Entries :  367

---Check whether there are duplicate data present after the clean----

Duplicate data :  0

In [35]:
#viewing statistical info about data set
clean_data.describe()

,Budget,Clicks,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value
count,89548.000000,89548.000000,89548.000000,89548.000000,89548.000000,89548.000000,89548.000000
mean,6.217213,1.203567,0.019603,120.213193,0.018450,0.370737,2.135266
std,7.616673,10.281681,0.116294,1031.055165,0.109503,3.068945,28.865181
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,50.000000,482.000000,6.950000,46671.000000,6.950000,147.260000,2355.520000

In [36]:
clean_data.shape

(89548, 19)

# Data Set Pre Process

In [50]:
clean_data.head()

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,2023-11-18,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,1,0.62%,0.16,162,0.16,0.16,0.00,Shopping,Target ROAS,--
1,2023-11-13,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,3,1.15%,0.18,261,0.18,0.53,0.00,Shopping,Target ROAS,--
2,2024-01-02,Paused,Display-Campaign Group 01,--,GBP,5.0,Daily,Paused,campaign paused; unknown,0,--,0.00,0,0.00,0.00,0.00,Display,Target ROAS,--
3,2024-01-07,Paused,Display-Campaign Group 01,--,GBP,5.0,Daily,Paused,campaign paused; unknown,0,--,0.00,0,0.00,0.00,0.00,Display,Target ROAS,--
4,2023-10-10,Paused,New Arrivals 05/10/2023,--,GBP,3.0,Daily,Paused,campaign paused; unknown,17,0.72%,0.23,2373,0.23,3.83,118.46,Shopping,Target ROAS,--

In [51]:
from sklearn.preprocessing import LabelEncoder

#creating an instance of labelencoder
labelencoder=LabelEncoder()

#assign numerical value and storing it in another
encoded_data=clean_data.iloc[0:]

encoded_data["Campaign status"]=labelencoder.fit_transform(clean_data["Campaign status"])
encoded_data["Campaign"]=labelencoder.fit_transform(clean_data["Campaign"])
encoded_data["Budget name"]=labelencoder.fit_transform(clean_data["Budget name"])
encoded_data["Currency code"]=labelencoder.fit_transform(clean_data["Currency code"])
encoded_data["Budget type"]=labelencoder.fit_transform(clean_data["Budget type"])
encoded_data["Status"]=labelencoder.fit_transform(clean_data["Status"])
encoded_data["Status reasons"]=labelencoder.fit_transform(clean_data["Status reasons"])
encoded_data["Campaign type"]=labelencoder.fit_transform(clean_data["Campaign type"])
encoded_data["Bid strategy type"]=labelencoder.fit_transform(clean_data["Bid strategy type"])
encoded_data["Campaign group"]=labelencoder.fit_transform(clean_data["Campaign group"])

In [52]:
encoded_data.head()

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,2023-11-18,1,87,0,0,3.0,0,4,7,1,0.62%,0.16,162,0.16,0.16,0.00,4,8,0
1,2023-11-13,1,87,0,0,3.0,0,4,7,3,1.15%,0.18,261,0.18,0.53,0.00,4,8,0
2,2024-01-02,1,39,0,0,5.0,0,4,7,0,--,0.00,0,0.00,0.00,0.00,0,8,0
3,2024-01-07,1,39,0,0,5.0,0,4,7,0,--,0.00,0,0.00,0.00,0.00,0,8,0
4,2023-10-10,1,87,0,0,3.0,0,4,7,17,0.72%,0.23,2373,0.23,3.83,118.46,4,8,0

In [53]:
encoded_data.shape

(89548, 19)

In [54]:
encoded_data

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,2023-11-18,1,87,0,0,3.0,0,4,7,1,0.62%,0.16,162,0.16,0.16,0.00,4,8,0
1,2023-11-13,1,87,0,0,3.0,0,4,7,3,1.15%,0.18,261,0.18,0.53,0.00,4,8,0
2,2024-01-02,1,39,0,0,5.0,0,4,7,0,--,0.00,0,0.00,0.00,0.00,0,8,0
3,2024-01-07,1,39,0,0,5.0,0,4,7,0,--,0.00,0,0.00,0.00,0.00,0,8,0
4,2023-10-10,1,87,0,0,3.0,0,4,7,17,0.72%,0.23,2373,0.23,3.83,118.46,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89910,2023-06-06,2,56,0,0,1.0,0,5,17,0,--,0.00,0,0.00,0.00,0.00,4,0,0
89911,2023-10-12,2,56,0,0,1.0,0,5,17,0,--,0.00,0,0.00,0.00,0.00,4,0,0
89912,2023-08-15,2,22,0,0,10.0,0,5,11,0,--,0.00,0,0.00,0.00,0.00,4,2,0
89913,2023-10-18,2,22,0,0,10.0,0,5,11,0,--,0.00,0,0.00,0.00,0.00,4,2,0
89914,2023-10-20,2,22,0,0,10.0,0,5,11,0,--,0.00,0,0.00,0.00,0.00,4,2,0

In [55]:
encoded_data['CTR']=encoded_data['CTR'].str.replace(r'--', r'0.00')

In [56]:
encoded_data['CTR'] = (pd.to_numeric(encoded_data['CTR'].str[:-1])
                            .div(100)
                            .mask(encoded_data['CTR'] == '%', 0))

In [58]:
encoded_data.head(2)

,Day,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Conv. value,Campaign type,Bid strategy type,Campaign group
0,2023-11-18,1,87,0,0,3.0,0,4,7,1,0.0062,0.16,162,0.16,0.16,0.0,4,8,0
1,2023-11-13,1,87,0,0,3.0,0,4,7,3,0.0115,0.18,261,0.18,0.53,0.0,4,8,0

In [59]:
#drop the Day column
test_data=encoded_data.drop(['Day'],axis=1)

x=test_data.drop('Conv. value',axis=1)
x.head()

,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Campaign type,Bid strategy type,Campaign group
0,1,87,0,0,3.0,0,4,7,1,0.0062,0.16,162,0.16,0.16,4,8,0
1,1,87,0,0,3.0,0,4,7,3,0.0115,0.18,261,0.18,0.53,4,8,0
2,1,39,0,0,5.0,0,4,7,0,0.0000,0.00,0,0.00,0.00,0,8,0
3,1,39,0,0,5.0,0,4,7,0,0.0000,0.00,0,0.00,0.00,0,8,0
4,1,87,0,0,3.0,0,4,7,17,0.0072,0.23,2373,0.23,3.83,4,8,0

In [60]:
x.shape

(89548, 17)

In [61]:
#seperate income column as y
y=test_data['Conv. value']
print(y)

0          0.00
1          0.00
2          0.00
3          0.00
4        118.46
          ...
89910      0.00
89911      0.00
89912      0.00
89913      0.00
89914      0.00
Name: Conv. value, Length: 89548, dtype: float64

### Split train and test data

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print("Training Set of Feature : ",x_train.shape)
print("Test Set of Features : ",x_test.shape)
print("Training set of Target : ",y_train.shape)
print("Test set of Target : ",y_test.shape)
x_train.head()

Training Set of Feature :  (71638, 17)
Test Set of Features :  (17910, 17)
Training set of Target :  (71638,)
Test set of Target :  (17910,)

,Campaign status,Campaign,Budget name,Currency code,Budget,Budget type,Status,Status reasons,Clicks,CTR,Avg. CPC,Impr.,Avg. cost,Cost,Campaign type,Bid strategy type,Campaign group
54314,2,69,0,0,2.00,0,5,17,0,0.000,0.00,0,0.00,0.00,4,0,0
22547,1,46,0,0,1.00,0,4,7,8,0.013,0.21,617,0.21,1.66,4,0,0
76062,1,97,0,0,7.94,0,4,7,0,0.000,0.00,0,0.00,0.00,2,2,0
75823,2,220,0,0,1.00,0,5,17,0,0.000,0.00,0,0.00,0.00,4,8,0
40900,2,35,0,0,5.00,0,5,11,0,0.000,0.00,0,0.00,0.00,4,6,0

## Prediction

In [63]:
from sklearn.naive_bayes import GaussianNB
BayesModel=GaussianNB()
BayesModel.fit(x_train,y_train)
y_predictedBayes=BayesModel.predict(x_test)
print("Predicted Value by the model\n",y_predictedBayes)
print("\nTrue Value of Test Set\n",y_test)

ValueError: Unknown label type: (array([0.00000e+00, 1.00000e-02, 2.00000e-02, ..., 1.63754e+03,
       1.66403e+03, 2.35552e+03]),)

In [32]:
#accuracy of the model (naive bayes classifier)
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score
accuracy=accuracy_score(y_test,y_predictedBayes)
precision=precision_score(y_test,y_predictedBayes)
f1=f1_score(y_test,y_predictedBayes)
recall=recall_score(y_test,y_predictedBayes)
print("Accuracy of the bayes classifier is : %.2f%%"%(accuracy*100))
print("Precision of the bayes classifier is : %.2f%%"%(precision*100))
print("Recall of the bayes classifier is : %.2f%%"%(recall*100))
print("F1_Score of the bayes classifier is : %.2f%%"%(f1*100))

Accuracy of the bayes classifier is : 78.95%
Precision of the bayes classifier is : 64.67%
Recall of the bayes classifier is : 32.05%
F1_Score of the bayes classifier is : 42.86%

### change features into scaler and then predict

In [33]:
from sklearn.preprocessing import StandardScaler

x0_train=StandardScaler().fit(x_train).transform(x_train)
x0_test=StandardScaler().fit(x_test).transform(x_test)
y0_train=y_train.iloc[0:]
y0_test=y_test.iloc[0:]
from sklearn.naive_bayes import GaussianNB
BayesModel2=GaussianNB()
BayesModel2.fit(x0_train,y0_train)
y0_predictedBayes=BayesModel2.predict(x0_test)
from sklearn.metrics import accuracy_score
accuracy1=accuracy_score(y0_predictedBayes,y0_test)
precision1=precision_score(y0_predictedBayes,y0_test)
f11=f1_score(y0_predictedBayes,y0_test)
recall1=recall_score(y0_predictedBayes,y0_test)
print("Accuracy of the bayes classifier is : %.2f%%"%(accuracy1*100))
print("Precision of the bayes classifier is : %.2f%%"%(precision1*100))
print("Recall of the bayes classifier is : %.2f%%"%(recall1*100))
print("F1_Score of the bayes classifier is : %.2f%%"%(f11*100))

Accuracy of the bayes classifier is : 79.73%
Precision of the bayes classifier is : 33.54%
Recall of the bayes classifier is : 67.94%
F1_Score of the bayes classifier is : 44.91%

# Distance to mean classifier

In [34]:
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import accuracy_score
ncModel=NearestCentroid()
ncModel.fit(x0_train,y0_train)
y_predictedFromNc=ncModel.predict(x0_test)
accuracyOfNc=accuracy_score(y_test,y_predictedFromNc)
print("Accuracy : ",(accuracyOfNc*100))

Accuracy :  73.37425348374254

In [36]:
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
KMModel=NearestCentroid()
KMModel.fit(x_train,y_train)
y_predictedKM=KMModel.predict(x_test)
accuracyOfKM=accuracy_score(y_test,y_predictedKM)
print("Accuracy : ",(accuracyOfKM*100))

Accuracy :  48.54014598540146